export const RESPONSIVE_SIZE_BREAKPOINT_LG = 1245
export const RESPONSIVE_SIZE_BREAKPOINT_MD = 1150
export const RESPONSIVE_SIZE_BREAKPOINT_SM = 1045
export const RESPONSIVE_SIZE_BREAKPOINT_S = 980
export const RESPONSIVE_SIZE_BREAKPOINT_SS = 820
export const RESPONSIVE_SIZE_BREAKPOINT_XS = 470
export const RESPONSIVE_SIZE_BREAKPOINT_XXS = 405

export const FALLBACK_EMAIL = process.env.FALLBACK_EMAIL